"""Ajout de sous-total et total

Revision ID: 8bc06ca1b5f6
Revises: 81e422f5e5b1
Create Date: 2021-07-23 00:55:17.641082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc06ca1b5f6'
down_revision = '81e422f5e5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
